import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import ImageHeader from './components/ImageHeader'
import Navbar from './components/Navbar'
import WhoWeAre from './components/WhoWeAre.js'
import Events from './components/Events'
import HomepagePosts from './components/HomepagePosts'
import { useState, useEffect, useRef } from 'react'
import { sanityClient } from '../sanity'
import Announcements from './components/Announcements'


export default function Home({ posts }) {
  console.log(posts)
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='scroll-smooth'>
      <Navbar />
      <ImageHeader />
      <WhoWeAre />
      <Events/>
      <HomepagePosts posts={posts} />
      <Announcements />
      </div>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export const getServerSideProps = async () => {
  const query = `*[_type == "post"]{
    _id,
    title,
    author-> {
    name
  },
    description,
    slug,
    publishedAt
  }`;

  const posts = await sanityClient.fetch(query)

  return {
    props: {
      posts
    }
  }
}